docs/config.yaml
docs/go.mod

Pre-requisite before https://github.com/apache/flink/pull/19571 can be completed

[FLINK-27394][Documentation] Make the Flink Elasticsearch documentation available as a Hugo Module, so it can be used in the Flink documentation

---

docs/go.mod

Running `hugo mod get -u github.com/apache/flink-connector-elasticsearch/docs` results in:
```
go: no module dependencies to download
go: github.com/apache/flink-connector-elasticsearch/docs@v0.0.0-20220425163347-3adb2b36dbc6: parsing go.mod: go.mod:1: mod files must use // comments (not /* */ comments)
go: no module dependencies to download
```

[hotfix] Changing comment structure for go.mod due to incorrect comment indicator

---

flink-connector-elasticsearch-base/src/main/java/org/apache/flink/connector/elasticsearch/sink/ElasticsearchSinkBuilderBase.java

The comment of ElasticsearchSinkBuilderBase has a typo.

[hotfix] Fix typo

---

flink-connector-elasticsearch6/pom.xml
flink-connector-elasticsearch7/pom.xml

We also need to add `flink-table-runtime` to avoid ClassNotFoundException on `org.apache.flink.table.shaded.com.jayway.jsonpath.spi.mapper.MappingProvider`

[FLINK-27757][Connector][Elasticsearch] Elasticsearch connector should not use `flink-table-planner` but `flink-table-planner-loader`

---

flink-connector-elasticsearch-base/src/main/java/org/apache/flink/connector/elasticsearch/sink/MapElasticsearchEmitter.java

The PR only aligns code in main repo, the MapElasticsearchEmitter class is used in PyFlink ES connector.
I will use this [ticket](https://issues.apache.org/jira/browse/FLINK-18887) to create the PyFlink ES Connector docs PR in this repo.

[FLINK-28107][python][connector/elasticsearch] Add a MapElasticsearchEmitter for PyFlink

---

docs/content.zh/docs/connectors/datastream/elasticsearch.md
docs/content/docs/connectors/datastream/elasticsearch.md

This PR fixes missing JAR download link for PyFlink users.

[FLINK-28904][python][docs] Add missing connector/format doc

---

flink-connector-elasticsearch6/src/main/java/org/apache/flink/connector/elasticsearch/sink/Elasticsearch6SinkBuilder.java

The PR makes use `RestHighLevelClient#bulkAsync` with RequestOptions instead of deprecated one as it recommended in javadoc [1] and as it is already done for elastic7 [2]
[1] https://github.com/elastic/elasticsearch/blob/6.8/client/rest-high-level/src/main/java/org/elasticsearch/client/RestHighLevelClient.java#L498-L507
[2] https://github.com/apache/flink/blob/master/flink-connectors/flink-connector-elasticsearch7/src/main/java/org/apache/flink/connector/elasticsearch/sink/Elasticsearch7SinkBuilder.java#L85-L88

[hotfix] Move away from deprecated RestHighLevelClient#bulkAsync

---

.github/workflows/ci.yml
pom.xml
tools/ci/log4j.properties

Runs the NoticeFileChecker on CI.
Additionally changes CI logging to output to the console, since otherwise we don't see any license checker output.

[FLINK-29310][ci] Check licensing 

---

.github/workflows/ci.yml
pom.xml

Also increases CI timeouts a little bit since they are too strict.
The parent source can be found here: https://github.com/zentol/flink-connector-parent/commit/a4bf8b302bb04490595316a4c086d01018db0809. It's largely what I remove from the ES pom.

[FLINK-29471] Use connector parent pom 

---

flink-sql-connector-elasticsearch6/src/main/resources/META-INF/NOTICE
flink-sql-connector-elasticsearch7/src/main/resources/META-INF/NOTICE
pom.xml

The PR to upgrade jackson bom to fix CVE-2022-42003 and CVE-2022-42004
It was applied for flink at FLINK-29468 and FLINK-29638

[FLINK-29468][FLINK-29638] Upgrade jackson bom to 2.13.4.20221013

---

.github/workflows/ci.yml

I'll add separate cron jobs that run against 1.16-SNAPSHOT/1.17-SNAPSHOT without caching later.

[FLINK-29931][ci] Pin binary version and cache binary

---

docs/content.zh/docs/connectors/table/elasticsearch.md
docs/content/docs/connectors/table/elasticsearch.md

There is a number of configuration properties which are not documented:
- sink.delivery-guarantee
- connection.request-timeout
- connection.timeout
- socket.timeout
 

[FLINK-30352] [connectors/elasticsearch] Document missing configuration properties

---

flink-connector-elasticsearch6/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch6DynamicSinkITCase.java

I found elasticsearch service in testcontainers may start up slower than  test case  leading to failure test.
Add a service  check strategy , which is http respose check for elasticsearch.

[FLINK-28177] for test containers add elasticsearch service really up check 

---

docs/content.zh/docs/connectors/datastream/elasticsearch.md
docs/content.zh/docs/connectors/table/elasticsearch.md
docs/content/docs/connectors/table/elasticsearch.md
docs/data/elastic.yml

- Chinese datastream document also use connector_artifact.
- Update ElasticSearch connector to use sql_connector_download_table shortcode. 
This pr should also backports to v3.0.

[FLINK-31759][es] Update ElasticSearch connector to use sql_connector_download_table shortcode.

---

pom.xml

Elasticsearch v3.0 won't compile when testing against Flink 1.17.1

[FLINK-32357] Elasticsearch v3.0 won't compile when testing against Flink 1.17.1

---

flink-connector-elasticsearch-e2e-tests/pom.xml
pom.xml

Commits are taken from https://github.com/apache/flink-connector-elasticsearch/pull/47
rebased and bumped to 1.18.3

[FLINK-28347][Test infrastructure] Upgrade testcontainers to 1.18.3

---

flink-connector-elasticsearch-base/pom.xml
flink-connector-elasticsearch-base/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/ElasticsearchApiCallBridge.java
flink-connector-elasticsearch-base/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/ElasticsearchRowDataLookupFunction.java
flink-connector-elasticsearch-base/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/ElasticsearchSinkBaseTest.java
flink-connector-elasticsearch-e2e-tests/flink-connector-elasticsearch-e2e-tests-common/pom.xml
flink-connector-elasticsearch-e2e-tests/flink-connector-elasticsearch-e2e-tests-common/src/main/java/org/apache/flink/streaming/tests/ElasticsearchLookupE2ECase.java
flink-connector-elasticsearch-e2e-tests/flink-connector-elasticsearch6-e2e-tests/pom.xml
flink-connector-elasticsearch-e2e-tests/flink-connector-elasticsearch6-e2e-tests/src/test/java/org/apache/flink/streaming/tests/Elasticsearch6LookupE2ECase.java
flink-connector-elasticsearch-e2e-tests/flink-connector-elasticsearch7-e2e-tests/pom.xml
flink-connector-elasticsearch-e2e-tests/flink-connector-elasticsearch7-e2e-tests/src/test/java/org/apache/flink/streaming/tests/Elasticsearch7LookupE2ECase.java
flink-connector-elasticsearch6/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch6DynamicSource.java
flink-connector-elasticsearch6/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch6DynamicTableFactory.java
flink-connector-elasticsearch6/src/main/java/org/apache/flink/streaming/connectors/elasticsearch6/Elasticsearch6ApiCallBridge.java
flink-connector-elasticsearch6/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
flink-connector-elasticsearch6/src/test/java/org/apache/flink/connector/elasticsearch/table/Elasticsearch6DynamicTableFactoryTest.java
flink-connector-elasticsearch6/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch6DynamicSinkITCase.java
flink-connector-elasticsearch6/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch6DynamicTableFactoryTest.java
flink-connector-elasticsearch7/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch7DynamicSource.java
flink-connector-elasticsearch7/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch7DynamicTableFactory.java
flink-connector-elasticsearch7/src/main/java/org/apache/flink/streaming/connectors/elasticsearch7/Elasticsearch7ApiCallBridge.java
flink-connector-elasticsearch7/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
flink-connector-elasticsearch7/src/test/java/org/apache/flink/connector/elasticsearch/table/Elasticsearch7DynamicTableFactoryTest.java
flink-connector-elasticsearch7/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch7DynamicSinkITCase.java
flink-connector-elasticsearch7/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch7DynamicTableFactoryTest.java

Now es connector could only be used as a sink, but in many business scenarios, we treat es as a index database, thus we should support to make it lookupable in flink.

[FLINK-29042][Connectors/ElasticSearch] Support lookup join for es connector

---

.github/workflows/push_pr.yml
.github/workflows/weekly.yml

The PR drops support for Flink 1.16 and adds 1.20 snapshot

[hotfix] Add support for Flink 1.20 and drop 1.16

---

flink-sql-connector-elasticsearch6/src/main/resources/META-INF/NOTICE
flink-sql-connector-elasticsearch7/src/main/resources/META-INF/NOTICE
pom.xml

jackson from 2.13.4.20221013 to 2.15.3
junit5 from 5.9.1 to 5.10.2
assertj from 3.23.1 to 3.25.3
testcontainers from 1.17.2 to 1.19.7
mockito from 3.4.6 to 3.12.4

[hotfix] Update dependencies

---

.github/workflows/push_pr.yml
.github/workflows/weekly.yml

The PR will allow to differentiate between elasticsearch connector statistics and others with name ci

[FLINK-34961] Use dedicated CI name for Elasticsearch connector to differentiate it in infra-reports

---

flink-connector-elasticsearch-base/src/main/java/org/apache/flink/connector/elasticsearch/sink/ElasticsearchSink.java
flink-connector-elasticsearch-base/src/main/java/org/apache/flink/connector/elasticsearch/sink/ElasticsearchSinkBuilderBase.java
flink-connector-elasticsearch-base/src/main/java/org/apache/flink/connector/elasticsearch/sink/ElasticsearchWriter.java
flink-connector-elasticsearch-base/src/main/java/org/apache/flink/connector/elasticsearch/sink/NetworkClientConfig.java
flink-connector-elasticsearch-base/src/test/java/org/apache/flink/connector/elasticsearch/sink/ElasticsearchSinkBuilderBaseTest.java
flink-connector-elasticsearch-base/src/test/java/org/apache/flink/connector/elasticsearch/sink/ElasticsearchWriterITCase.java

https://issues.apache.org/jira/browse/FLINK-34369
This is a preliminary PR that was tested locally with secure ES clusters. Plan is to get early feedback, add some tests, and test with deployed jobs.

[FLINK-34369][connectors/elasticsearch] Elasticsearch connector supports SSL context

---

.github/workflows/push_pr.yml
.github/workflows/weekly.yml
flink-connector-elasticsearch-base/src/test/java/org/apache/flink/connector/elasticsearch/sink/ElasticsearchWriterITCase.java
pom.xml

- Changed base flink version to 1.20.0
- Removed CI tests for 1.18.
- Fixed incompatibility in IT tests TestMailbox.
- Add Archunit violations for updated arch rules.
Successful run:
https://github.com/vahmed-hamdy/flink-connector-elasticsearch/actions/runs/11645464636

[FLINK-36651][Connectors/Elasticsearch] Fix IT test not compatible with 1.20, drop main branch tests for 1.18

---

flink-connector-elasticsearch-base/pom.xml
flink-connector-elasticsearch-e2e-tests/flink-connector-elasticsearch-e2e-tests-common/pom.xml
flink-connector-elasticsearch-e2e-tests/flink-connector-elasticsearch6-e2e-tests/pom.xml
flink-connector-elasticsearch-e2e-tests/flink-connector-elasticsearch7-e2e-tests/pom.xml
flink-connector-elasticsearch-e2e-tests/pom.xml
flink-connector-elasticsearch6/pom.xml
flink-connector-elasticsearch7/pom.xml
flink-connector-elasticsearch8/pom.xml
flink-sql-connector-elasticsearch6/pom.xml
flink-sql-connector-elasticsearch7/pom.xml
pom.xml

- since there are no breaking changes from the latest release v3.0.1 the version should be v3.1

[hotfix][Connector/Elasticsearch] Update version to 3.1-SNAPSHOT

---

docs/content.zh/docs/connectors/table/elasticsearch.md
docs/content/docs/connectors/table/elasticsearch.md

After FLINK-30352, the current doc is mismatched to the active default ES table connector, this PR targets to correct this.

[FLINK-36987][docs] Correct the docs to the active ES table connector

---

docs/content.zh/docs/connectors/datastream/elasticsearch.md
docs/content/docs/connectors/datastream/elasticsearch.md

There is no method named "ElasticsearchEmitter.static", it should be "ElasticsearchEmitter.static_index".

[FLINK-37265][docs] Document of python elasticsearch connector exeample has a little mistake
